version: "3.8"

services:
  # 1. Djangoアプリケーションを動かすサービス
  web:
    build: .
    command: gunicorn config.Attendance:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "80:8000" # サーバーの80番ポートをコンテナの8000番ポートに接続
    environment:
      - SECRET_KEY=YOUR_DJANGO_SECRET_KEY_HERE # 必ず自身のシークレットキーに書き換える
      - DATABASE_URL=mysql://user:password@db:3306/dbname
    depends_on:
      - db

  # 2. MySQLデータベースを動かすサービス
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "dbname"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root_password" # 適当なパスワードを設定
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: